language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
addons:
  code_climate:
    repo_token: 049ea25172959f370cb6c3e2b112741d952aa787edaad4e1b505463fc5efc145
after_script:
  - codeclimate-test-reporter < lcov.info
script:
  - npm test --cover
